version: '3'

services:
  server:
    image: carlasim/carla:0.9.15
    privileged: true
    devices:
      - "/dev/dri:/dev/dri"
    environment:
      - DISPLAY:${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES:all
      - XAUTHORITY:${XAUTHORITY}
      - SDL_VIDEODRIVER:x11
    command: ["/bin/bash", "./CarlaUE4.sh", "-prefernvidia", "-RenderOffScreen"]
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: "all"
            capabilities: [gpu]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /usr/share/vulkan/icd.d:/usr/share/vulkan/icd.d

  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    image: devcontainer
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace:cached

